0-module
js-tasks-ru/jsbasic-20230428_nikkib pull request #1
Opened 2023-04-29 17:39 UTC by VeronikaMol

2023-04-29 17:39 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2023-04-30 10:54 UTC, SinimaWath requested changes

2023-04-30 10:54 UTC, SinimaWath commented on 0-module/1-task/index.js
> +  alert (result);
Давай уберем alert, по условию, задача должно просто возвращать результат из функции

2023-04-30 10:54 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-04-30 14:16 UTC, VeronikaMol commented on 0-module/1-task/index.js
> +  alert (result);
спасибо, добавляла для проверки, убрала

2023-05-01 10:30 UTC, SinimaWath approved these changes
Все ок

2023-05-01 10:30 UTC, merged