5-module
js-tasks-ru/jsbasic-20230428_nikkib pull request #6
Opened 2023-05-21 12:19 UTC by VeronikaMol

2023-05-21 12:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-21 12:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-21 12:28 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-23 15:00 UTC, SinimaWath requested changes

2023-05-23 15:00 UTC, SinimaWath commented on 5-module/1-task/index.js
> +  });
Тут не стоит использовать делегирование, а проще выбрать ДОМ елемент кнопки и на него подписаться:
```
const button = document.getElementsByClassName('hide-self-button')[0];

button.addEventListener('click', ....)
```

2023-05-23 15:00 UTC, SinimaWath commented on 5-module/2-task/index.js
> +  });
Тут тоже проще написать без делегирование

2023-05-23 15:00 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  document.addEventListener('click', function(event) {
Тут можно использовать делегирование, но стоит "уменьшить глубину" делегирования. И повесить обработчик события на корень карусели: `const carousel = document.querySelector('.carousel')`

2023-05-24 05:36 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-24 05:38 UTC, VeronikaMol commented on 5-module/3-task/index.js
> +  document.addEventListener('click', function(event) {
все поправила, спасибо

2023-05-26 13:11 UTC, SinimaWath approved these changes

2023-05-26 13:12 UTC, merged