6-module
js-tasks-ru/jsbasic-20230428_nikkib pull request #7
Opened 2023-05-28 12:51 UTC by VeronikaMol

2023-05-28 12:51 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-29 13:55 UTC, SinimaWath requested changes

2023-05-29 13:55 UTC, SinimaWath commented on 6-module/3-task/index.js
> +      let iid = item.id;
Давай формирование Продукта так же вынесем в шаблон, чтобы сразу было понятно из чего состоит Елемент. Использую шаблонную строку:
```
`
      <div class="carousel__slide"  data-id="${id}">
        <img class="carousel__img" alt="slide" src="${....}">
        <div class="carousel__caption">
          <span class="carousel__price">${price}</span>
          <div class="carousel__title">${title}</div>
          <button type="button" class="carousel__button">
          <img src="/assets/images/icons/plus-icon.svg" alt="icon">
          </button>
        </div>
      </div>
    `

```

2023-05-30 04:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-30 04:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-30 05:30 UTC, VeronikaMol commented
Спасибо, поправила. Только я уже задачку из следующего модуля посмотреть скачала ) автоматическая проверка не проходит

2023-05-30 12:22 UTC, SinimaWath commented
Тогда подожду пока решишь задачку из след модуля

2023-06-01 15:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-01 15:04 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-01 18:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-01 18:55 UTC, SinimaWath requested changes

2023-06-01 18:55 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    image.setAttribute('src', '/assets/images/products/' + this.#product.image);
Это осталось не поправленым.

Давай формирование Продукта так же вынесем в шаблон, чтобы сразу было понятно из чего состоит Елемент. Использую шаблонную строку:
```
`
      <div class="carousel__slide"  data-id="${id}">
        <img class="carousel__img" alt="slide" src="${....}">
        <div class="carousel__caption">
          <span class="carousel__price">${price}</span>
          <div class="carousel__title">${title}</div>
          <button type="button" class="carousel__button">
          <img src="/assets/images/icons/plus-icon.svg" alt="icon">
          </button>
        </div>
      </div>
    `

```

2023-06-01 18:55 UTC, SinimaWath commented on 6-module/3-task/index.js
> +      image.setAttribute('src', '/assets/images/carousel/' + item.image);
Тут Давай формирование Продукта так же вынесем в шаблон, чтобы сразу было понятно из чего состоит Елемент. Использую шаблонную строку:
```
`
      <div class="carousel__slide"  data-id="${id}">
        <img class="carousel__img" alt="slide" src="${....}">
        <div class="carousel__caption">
          <span class="carousel__price">${price}</span>
          <div class="carousel__title">${title}</div>
          <button type="button" class="carousel__button">
          <img src="/assets/images/icons/plus-icon.svg" alt="icon">
          </button>
        </div>
      </div>
    `

```

2023-06-01 18:55 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    ribbon.append(arrowLeft);
Это было бы проще читать в шаблоне:
```
<button class="ribbon__arrow ribbon__arrow_left">
<img src="/assets/images/icons/angle-icon.svg" alt="icon">
</button>
```

2023-06-01 18:55 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    ribbonInner.firstElementChild.classList.add('ribbon__item_active');
Это было бы проще читать в шаблоне:
```
<nav class="ribbon__inner">
....
</nav>
```

2023-06-01 18:55 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    ribbon.append(arrowRight);
Это было бы проще читать в шаблоне:
```
<button class="ribbon__arrow ribbon__arrow_right ribbon__arrow_visible">
<img src="/assets/images/icons/angle-icon.svg" alt="icon">
</button>
```

2023-06-02 05:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-02 05:32 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-02 09:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-02 09:45 UTC, VeronikaMol commented
Вроде все поправила... Но я совсем запуталась в 4 задаче 7 модуля - в браузере все работает, и по клику, и drag-and-drop, значение ползунка меняется, закрашенная ширина отрисовывается, но тесты не проходят. Третий день сижу, туда-сюда гоняю этот таск, не могу понять где ошибка

2023-06-03 14:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-03 14:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-05 18:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-06 15:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-06 15:27 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-06 15:29 UTC, VeronikaMol commented
8 модуль добавлен. Но 4 задача 7 модуля все еще не пускает PR )

2023-06-07 07:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-10 17:33 UTC, SinimaWath approved these changes

2023-06-10 17:36 UTC, merged